"""add owner_id to projects

Revision ID: 5f0610ba0008
Revises: 0c8c3ee92c3a
Create Date: 2026-10-06 15:49:10.893639

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f0610ba0008"
down_revision: str | Sequence[str] | None = "0c8c3ee92c3a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # owner_id is added in three steps because projects already has rows,
    # and a NOT NULL column can't be added to a table with data.
    # Backfill decision: existing projects are assigned to the oldest user
    # (lowest id). If there are no users, orphan projects are deleted.
    op.add_column("projects", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.execute("UPDATE projects SET owner_id = (SELECT min(id) FROM users)")
    op.execute("DELETE FROM projects WHERE owner_id IS NULL")
    op.alter_column("projects", "owner_id", nullable=False)
    op.create_index(
        op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_projects_owner_id_users"),
        "projects",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_projects_owner_id_users"), "projects", type_="foreignkey"
    )
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_column("projects", "owner_id")
    # ### end Alembic commands ###
