"""add index on tasks.assignee_id

Revision ID: 63ee7d1316b7
Revises: 55911c407807
Create Date: 2026-10-06 19:12:57.006294

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63ee7d1316b7"
down_revision: str | Sequence[str] | None = "55911c407807"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_tasks_assignee_id"), "tasks", ["assignee_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_assignee_id"), table_name="tasks")
    # ### end Alembic commands ###
